version: '3'
services:
  mongodb:
    image: mongo
    volumes:
     - mongodata:/data/db
  httpd:
    build:
      context: ./conformance-suite/httpd
    ports:
     - "8443:8443"
    depends_on:
     - server
  server:
    build:
      context: ./conformance-suite/server-dev
#      args:
#        JAR_FILE: /server/fapi-test-suite.jar
    volumes:
     - ./conformance-suite/target/fapi-test-suite.jar:/server/fapi-test-suite.jar
#    environment:
#     - JAR_FILE=target/fapi-test-suite.jar
    command: >
      bash -c
      "ls -l /server &&
      chmod +x /server/fapi-test-suite.jar &&
      java
      -jar /server/fapi-test-suite.jar
      -Djava.security.egd=file:/dev/./urandom
      --fintechlabs.base_url=https://localhost.emobix.co.uk:8443
      --fintechlabs.devmode=true
      --fintechlabs.startredir=true"
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
volumes:
  mongodata: