# version: '3.6'
# services:
#   conformance_suite:
#     privileged: yes
#     build:
#       context: ./keycloak-fapi-conformance-suite
#     volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ${MAVEN_HOME:-~/.m2}:/root/.m2
#     environment:
    #  - OPENID_CONFORMANCE_SUITE_GIT_URL=${OPENID_CONFORMANCE_SUITE_GIT_URL}
    #  - KEYCLOAK_BASE_IMAGE=${KEYCLOAK_IMAGE:-jboss/keycloak:latest}
    #  - FAPI_TEST_JSON_CONFIG_FILENAME=${CONFIG_FILENAME:-fapi-rw-id2-with-private-key-PS256-PS256.json}
    #  - KEEP_ALIVE=${KEEP_ALIVE:-false}
    #  - AUTOMATE_TESTS=${AUTOMATE_TESTS:-true}