version: '3'
services:
  conformance_suite:
    privileged: yes
    build:
      context: ./keycloak-fapi-conformance-suite
    volumes:
     - mavencache:/root/.m2
     - //var/run/docker.sock:/var/run/docker.sock
volumes:
  mavencache:

