version: '3.6'
services:
  load_balancer:
    build:
      context: ./load-balancer
    ports:
     - "443:443"
    environment:
     - KEYCLOAK_FQDN=${KEYCLOAK_FQDN}
     - RESOURCE_FQDN=${RESOURCE_FQDN}
     - CONFORMANCE_SUITE_FQDN=${CONFORMANCE_SUITE_FQDN}
    depends_on:
     - keycloak
     - keycloak_gatekeeper
    networks:
      default:
        aliases:
         - ${KEYCLOAK_FQDN}
         - ${RESOURCE_FQDN}
         - ${CONFORMANCE_SUITE_FQDN}
  keycloak:
    build:
      context: ./keycloak
      args:
        KEYCLOAK_BASE_IMAGE: ${KEYCLOAK_BASE_IMAGE}
    ports:
     - "8787:8787"
    environment:
     - KEYCLOAK_USER=${KEYCLOAK_USER}
     - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
    command: "-b 0.0.0.0 -Djboss.socket.binding.port-offset=1000 --debug"
  keycloak_gatekeeper:
    build:
      context: ./keycloak-gatekeeper
    environment:
     - KEYCLOAK_FQDN=${KEYCLOAK_FQDN}
     - KEYCLOAK_REALM=${KEYCLOAK_REALM}
    volumes:
     - ./https/server.pem:/etc/x509/https/tls.crt
     - ./https/server-key.pem:/etc/x509/https/tls.key
     - ./https/client-ca.pem:/etc/x509/https/client-ca.crt
    depends_on:
     - resource_server
     - keycloak
  resource_server:
    build:
      context: ./resource-server
  client_jwks_server:
    build:
      context: ./client_private_keys
    command: /keys
  test_runner:
    build:
      context: ./test-runner
    environment:
     - FAPI_TEST_JSON_CONFIG_FILENAME=${FAPI_TEST_JSON_CONFIG_FILENAME}
     - AUTOMATE_TESTS=${AUTOMATE_TESTS}
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ./fapi-conformance-suite-configs:/json-config
    depends_on:
     - load_balancer
     - keycloak
     - server
  mongodb:
    image: mongo
    volumes:
     - mongodata:/data/db
  httpd:
    build:
      context: ./conformance-suite/httpd
    ports:
      - "8443:8443"
    depends_on:
      - server
  server:
    build:
      context: ./conformance-suite
      args:
        CONFORMANCE_SERVER: https://${CONFORMANCE_SUITE_FQDN}
    ports: 
      - "9999:9999"
    volumes:
      - ~/.m2:/root/.m2
      # - ./automation-files/run-tests.sh:/conformance-suite/run-tests.sh
    environment:
      - CONFORMANCE_SERVER=https://${CONFORMANCE_SUITE_FQDN}
      - CONFORMANCE_DEV_MODE=1
    links:
      - mongodb:mongodb
    depends_on:
      - mongodb
      - keycloak
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
volumes:
  mongodata:
