version: '3.6'
services:
  mongodb:
    image: mongo
    volumes:
     - mongodata:/data/db
  httpd:
    build:
      context: ./conformance-suite/httpd
    ports:
     - "8443:8443"
    depends_on:
     - server
  server:
    build:
      context: ./conformance-suite
      args:
        CONFORMANCE_SUITE_FQDN: ${CONFORMANCE_SUITE_FQDN}
    volumes:
     - ~/.m2:/root/.m2
    environment:
     - CONFORMANCE_SUITE_FQDN=${CONFORMANCE_SUITE_FQDN}
    links:
     - mongodb:mongodb
    depends_on:
     - mongodb
     - keycloak
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
volumes:
  mongodata: