FROM maven:3.6.3-openjdk-11-slim as builder
# add all files - could have some exclusions here
ADD . .
# build openId FAPI test suite spring boot server project
RUN mvn -DskipTests -Dmaven.repo.local=/root/.m2 package spring-boot:repackage && chmod +x ./target/fapi-test-suite.jar

# start on a fresh image because we only need the jar
FROM openjdk:11.0.3-jdk-slim-stretch
COPY --from=builder /target/fapi-test-suite.jar fapi-test-suite.jar
# the server app requires redir to run
RUN apt-get update && apt-get install redir
ENV BASE_URL https://localhost:8443
ENV MONGODB_HOST mongodb
EXPOSE 8080
EXPOSE 9090