FROM maven:3.6.3-openjdk-11-slim as builder
# add all files - could have some exclusions here
ADD . .
# the server app requires redir to run
RUN apt-get update && apt-get install redir
ENV BASE_URL https://${CONFORMANCE_SUITE_FQDN}
ENV MONGODB_HOST mongodb
EXPOSE 8080
EXPOSE 9090
CMD [ "sh", "./server-entrypoint.sh" ]